### PR TITLE
Fix Gruvbox foreground color

### PR DESCRIPTION
**Pull request by McSinyx**
I'm not sure if the color is incorrect for other colorschemes though.

### CODE REVIEW

**Comment by bezmi** [comment]
Thanks for the pull request. According to the styling guidelines on the [base16 home page](http://chriskempson.com/projects/base16/), base05 should be the default foreground colour. Is there a particular reason why you have changed it to base06?

**Comment by McSinyx** [comment]
According to the Gruvbox [palette](https://github.com/morhetz/gruvbox#palette), base05 is currently *not* foreground color. I guess the problem was with generating the base colors in the first place.

**Comment by bezmi** [comment]
Thanks for the response. I auto-assigned colours based on [chriskempson/base16](https://github.com/chriskempson/base16), which states that [dawikur/base16-gruvbox-scheme](https://github.com/dawikur/base16-gruvbox-scheme) is the "correct" scheme repository for base16 gruvbox colours. It's clear that the colours here don't match up with those defined by the original author of gruvbox.

The reason for the difference is that the base16 guidelines require base00 to base07 to be variations of shade from darkest to lightest (other way around for light themes), and for base05 to be the default foreground. As this is a base16 colours repository, I'm inclined to keep the colours as they are and leave base05 as foreground for consistency. 

You could host your own gruvbox-tridactyl repo with the correct colours and submit a pull request to the main tridactyl repo to include it in the docs.

**Comment by McSinyx** [comment]
I was using your repository as the sample to build my own theme and noticed the imprecise foreground used for gruvbox and I thought you'd need to be informed. It it totally up to you, though, on how to handle this situation, but again, `#3c3836` is the fg for light variant (not `#504945`) and `#ebdbb2` is for the dark one (not `#d5c4a1`). I think you should, as the maintainer, inform to both @dawikur and @chriskempson to prevent this inaccuracy from prolonging.

**Comment by dawikur** [comment]
Hi guys. Thanks for letting me know about this.

(let's consider just light-medium palette, rest may be extrapolated)
Accordingly to http://chriskempson.com/projects/base16/
the default color is, as you said, `base05` and gruvbox defines it to `#3c3836`.
But **base16** defines also `base06` and `base07` which seems to be lighter and lighter
respectively. Unfortunately **gruvbox** defines only one lighter color: `#282828`. This
caused me to shift the `baseXX` colors by one tint. So basically what @bezmi  wrote :)

Should I instead break the **base00**-**base07** shades order and use something different
for *base07**? Maybe **gray** `#928374`? or **bg4** `#a89984`? 
@chriskempson what is your opinion on this?

**Pull request closed without merging**
